<?xml version="1.0" encoding="utf-8"?><Database Name="T2017FB_CabinetBooking" Class="CabinetBookingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=idev.hitdm.com;Initial Catalog=T2017FB_CabinetBooking;Persist Security Info=True;User ID=Training_2017_Fall_Beginners_Projects" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="T2017FB_CabinetBookingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Appointments" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoctorAndSpecility" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppointmentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Speciality_Appointment" Member="Speciality" ThisKey="DoctorAndSpecility" OtherKey="ID" Type="Speciality" IsForeignKey="true" />
      <Association Name="User_Appointment" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Specialities" Member="Specialities">
    <Type Name="Speciality">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UeserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Speciality" Member="Speciality1" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Speciality_Appointment" Member="Appointments" ThisKey="ID" OtherKey="DoctorAndSpecility" Type="Appointment" />
      <Association Name="User_Speciality" Member="User" ThisKey="UeserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Appointment" Member="Appointments" ThisKey="ID" OtherKey="UserID" Type="Appointment" />
      <Association Name="User_Speciality" Member="Specialities" ThisKey="ID" OtherKey="UeserID" Type="Speciality" />
    </Type>
  </Table>
</Database>